permalink: /:categories/:title.html
url: "https://tech.mof-mof.co.jp/"
blog_title: "もふもふ技術部"
description: >
  もふもふ技術部は、mofmof inc.のエンジニア達のテックブログです。試してみた技術のログをアップしていきます。
author:
  name: HOGE
authors:
  aharada:
    name: "原田 敦"
    img_name_path: "/images/users/aharada.jpg"
    aboutme: "「作って人をしあわせにする」ことがミッション。多くの人を幸せにするプロダクトを世に送り出すことが、クリエイターにとって至上の幸せだと思ってます。デスマを憎んで人を憎まず。よりよいソフトウェアは、よりよいチームから生まれると思ってます。"
  shwld:
    name: "橘 周世"
    img_name_path: "/images/users/shwld.jpg"
    aboutme: "Electron, AWS, React, 機械学習, Dockerなどやってます。Electronで自分のためのノートとか作ってます"
  tishii:
    name: "石井 智康"
    img_name_path: "/images/users/tishii.jpg"
    aboutme: "旅をこよなく愛する雑食系エンジニア。認定スクラムマスター。「楽しく作る」を極めたい。エンジニアの世界とビジネスの世界（非ITの世界）を幸せにつなげていくことをテーマに活動をしています。"
  knishiyama:
    name: "西山 歓司"
    img_name_path: "/images/users/knishiyama.jpg"
    aboutme: "大手企業でSEOの知識を習得後、大規模サイトの構築、運用業務に携わり、デザイン事務所へ転職。デザインを学びながら人生模索しながら今にいたる。特技としてマウスとキーボードを駆使して、パソコンを使うことができます。"
  ysakuma:
    name: "佐久間　祐太"
    img_name_path: "/images/users/ysakuma.jpg"
    aboutme: "水は苦手だけど海辺が好きな男です。前職は典型的SEなので、mofmofスタイルで刺激ある日々を送っています。家族には呆れられてますが、絶対に沖縄で暮らしてやる。"
  nekikara:
    name: "荒木 健"
    img_name_path: "/images/users/user.jpg"
    aboutme: "京都在住のエンジニア。自分の技術で世界にインパクトを与えるプロダクトを作りたい。仕事はRails、趣味は機械学習。Stanford University Machine Learning course certificate 取得"
  karamage:
    name: "柿本 匡章"
    img_name_path: "/images/users/karamage.jpg"
    aboutme: "こんにちは、からまげです。 ハイパーアプリクリエーターとしてスマホアプリやWebサービスを作る仕事をしています。 1978年9月福岡県生まれの九州男児です。趣味はアニメやゲームを嗜みます"
  yamagata:
    name: "山形 孝造"
    img_name_path: "/images/users/yamagata.png"
    aboutme: "アイデアを形にするのが好きなソフトウェアエンジニアです。音楽と料理が好きです。ギターとかベース弾いたり走ったりもします。"
  miyata:
    name: "宮田 裕貴"
    img_name_path: "/images/users/miyata.jpeg"
    aboutme: "SIerからmofmofにジョイン。ハイレベルなエンジニアになるべく、日々修行中。趣味は筋トレ。映画「Fight Club」のタイラー・ダーテンのような鋼の肉体を手に入れたい。"
  iwai:
    name: "岩井 寿樹"
    img_name_path: "/images/users/iwai.png"
    aboutme: "ものづくりの人として成長するためにSIerからmofmofにやってきました。プロダクトに関わる全ての人を喜ばせたい。卓球室のある家を建てるのが夢。"
  sakashita:
    name: "坂下 凜"
    img_name_path: "/images/users/sakashita.jpg"
    aboutme: "JavaからRubyに転向したエンジニアです。最近はGo/Swift/Reactにトライしています。趣味はサッカーと読書です。"
disqus_shortname: ""
copyright_year: "2015"
google_analytics_code: "UA-44232253-15"
twitter: ""
github: "mofmof"
facebook: ""
linkined_url: ""
kramdown:
  input: GFM
#markdown: redcarpet
#redcarpet:
#  extensions: [tables,autolink,strikethrough]

exclude: [vendor]
